```{r}
rain=read.csv("weatherAus.csv")
new.data <- na.omit(rain)
```

```{r}
new.data$Location=(factor(new.data$Location))
new.data$WindGustDir=(factor(new.data$WindGustDir))
new.data$WindDir9am=(factor(new.data$WindDir9am))
new.data$WindDir3pm=(factor(new.data$WindDir3pm))
new.data$RainToday=(factor(new.data$RainToday))
new.data$RainTomorrow=(factor(new.data$RainTomorrow))
new.data$Date=as.Date(new.data$Date)
ydate = factor(format(new.data$Date,'%m'))
new.data$Date=ydate
```

```{r}
set.seed(2)
train.index <- sample(c(1:dim(new.data)[1]), dim(new.data)[1]*0.6)
traindf <- new.data[train.index,-23]
validdf <- new.data[-train.index,-23]
```

```{r}
bestfr=subset(new.data[,], select=c(MinTemp ,MaxTemp , Rainfall ,Sunshine , WindGustSpeed, WindSpeed9am ,WindSpeed3pm , Humidity9am , Humidity3pm , Pressure9am , Pressure3pm , Cloud9am , Cloud3pm ,WindGustDir,WindDir9am , WindDir3pm,RainToday,Date))
corr=bestfr[,1:13]
sapply(corr,class)
```

```{r}
library("FactoMineR")
library("factoextra")
pc=prcomp(corr)



```

```{r}

newdat=as.data.frame(pc$x[,1:2])
newdat$response=new.data[,24]
newdat$WindGustDir=bestfr[,14]
newdat$WindDir9am=bestfr[,15]
newdat$WindDir3pm=bestfr[,16]
newdat$RainToday=bestfr[,17]
newdat$Date=bestfr[,18]
newdat$Location=new.data[,2]


```

```{r}
set.seed(2)
train.index <- sample(c(1:dim(newdat)[1]), dim(newdat)[1]*0.6)
train.df <- newdat[train.index,]
valid.df <- newdat[-train.index,]
```

```{r}

```

```{r}
library(caret)
confusionMatrix(conf)
```

```{r}
library(randomForest)
library(caret)
model=randomForest(response~.,data=train.df,mtry=6,ntree=600)
y=valid.df$response
rf.pred = predict(model,valid.df)
conf=table(rf.pred,y)
importance(model)
plot(model)
confusionMatrix(conf)

```

```{r}
print("Confusion matrix and evaluation measures for Random forest fitted using PC's")
```

```{r}
var <- get_pca_var(res.pca)
newdat=as.data.frame(var$coord[,1:5])
```

```{r}
fviz_pca_var(res.pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE # Avoid text overlapping
             )
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
(var$contrib)

```

```{r}
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )

```

```{r}


```

```{r}
logit.reg <- glm(RainTomorrow ~ Date + MinTemp + MaxTemp + 
    Rainfall + Evaporation + Sunshine + WindGustSpeed  + 
    WindDir3pm + WindSpeed9am + WindSpeed3pm + Humidity3pm + 
    Pressure9am + Pressure3pm + Cloud3pm , data =traindf , family = "binomial",control = list(maxit = 50, epsilon=1))
logit.reg.pred <- predict(logit.reg,validdf, type = "response")
pred=ifelse(logit.reg.pred>0.5,"Yes","No")
conf=table(pred,validdf$RainTomorrow)
print("result for logistic regression model using the selected variables")
confusionMatrix(conf)
summary(logit.reg)

```

```{r}
stepw1=step(logit.reg,trace = 0)
summary(stepw1)
```

```{r}
print("Results for logistic regression using selected variables")
logit.reg.pred <- predict(stepw1,validdf, type = "response")
pred=ifelse(logit.reg.pred>0.5,"Yes","No")
conf=table(pred,validdf$RainTomorrow)
print("result for logistic regression model using all the variables")
confusionMatrix(conf)
summary(logit.reg)
```

