```{r}
rain=read.csv("weatherAus.csv")
```

```{r}
new.data <- na.omit(rain)
new.data$Date= NULL

```

```{r}
new.data$Location=as.numeric(factor(new.data$Location))
new.data$WindGustDir=as.numeric(factor(new.data$WindGustDir))
new.data$WindDir9am=as.numeric(factor(new.data$WindDir9am))
new.data$WindDir3pm=as.numeric(factor(new.data$WindDir3pm))
new.data$RainToday=as.numeric(factor(new.data$RainToday))
new.data$RainTomorrow=as.numeric(factor(new.data$RainTomorrow))
```

```{r}
logit.reg <- glm(new.data$RainTomorrow~ ., data = new.data[,-23], family = "binomial",control = list(maxit = 50, epsilon=1))
options(scipen=999)
summary(logit.reg)
```

```{r}
stepw1=step(logit.reg,trace = 0)
summary(stepw1)
```

```{r}
chisq.test(new.data$Humidity9am,new.data$RISK_MM,correct = FALSE)
```

```{r}
best <- glm(new.data$RainTomorrow~Location + MinTemp + MaxTemp + 
    Rainfall + Evaporation + Sunshine + WindGustSpeed + WindDir9am + 
    WindDir3pm + WindSpeed9am + WindSpeed3pm + Humidity3pm + 
    Pressure9am + Pressure3pm + Cloud9am + Cloud3pm + RainToday + 
    RISK_MM, data = new.data[,], family = "binomial",control = list(maxit = 50, epsilon=1))
summary(best)
```

```{r}

```

```{r}

```

